name: Terraform Manual Deploy 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            eu-north-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./envs/${{ github.event.inputs.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./envs/${{ github.event.inputs.environment }}

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="${{ github.event.inputs.environment }}.tfvars"
        working-directory: ./envs/${{ github.event.inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="${{ github.event.inputs.environment }}.tfvars"
        working-directory: ./envs/${{ github.event.inputs.environment }}
